"""Share functionality for Link Safety Checker results."""
import tkinter as tk
from tkinter import messagebox, filedialog
from datetime import datetime
import json
import io

try:
    import pyperclip
    PYPERCLIP_AVAILABLE = True
except ImportError:
    PYPERCLIP_AVAILABLE = False

try:
    import qrcode
    from PIL import Image, ImageTk
    QR_AVAILABLE = True
except ImportError:
    QR_AVAILABLE = False


class ShareManager:
    """Manages sharing of scan results in various formats."""
    
    @staticmethod
    def format_text_report(url, verdict, timestamp=None):
        """Generate plain text report.
        
        Args:
            url: The scanned URL
            verdict: The FinalSecurityVerdict object
            timestamp: Optional timestamp string
            
        Returns:
            Formatted text report
        """
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        
        lines = []
        lines.append("=" * 70)
        lines.append("LINK SAFETY CHECKER - SCAN REPORT")
        lines.append("Developed by AlesSystems")
        lines.append("=" * 70)
        lines.append("")
        lines.append("URL INFORMATION")
        lines.append("-" * 70)
        lines.append(f"URL: {url}")
        lines.append(f"Scan Date: {timestamp}")
        lines.append("")
        lines.append("SECURITY STATUS")
        lines.append("-" * 70)
        
        status = verdict.verdict.upper()
        status_emoji = {
            'SAFE': '✅',
            'SUSPICIOUS': '⚠️',
            'DANGEROUS': '🚫'
        }.get(status, '❓')
        
        lines.append(f"Status: {status_emoji} {status}")
        
        if hasattr(verdict, 'rule_score'):
            lines.append(f"Risk Score: {verdict.rule_score}/100")
        
        if hasattr(verdict, 'api_data') and verdict.api_data:
            threat_types = verdict.api_data.get('threat_types', [])
            if threat_types:
                lines.append(f"Threat Types: {', '.join(threat_types)}")
        
        if hasattr(verdict, 'reasons') and verdict.reasons:
            lines.append("")
            lines.append("REASONS")
            lines.append("-" * 70)
            for reason in verdict.reasons:
                lines.append(f"• {reason}")
        
        lines.append("")
        lines.append("=" * 70)
        lines.append("This report was generated by Link Safety Checker")
        lines.append("For more information, visit: https://github.com/AlesSystems")
        lines.append("=" * 70)
        
        return "\n".join(lines)
    
    @staticmethod
    def format_markdown_report(url, verdict, timestamp=None):
        """Generate Markdown report.
        
        Args:
            url: The scanned URL
            verdict: The FinalSecurityVerdict object
            timestamp: Optional timestamp string
            
        Returns:
            Formatted Markdown report
        """
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        
        lines = []
        lines.append("# Link Safety Checker - Scan Report")
        lines.append("")
        lines.append("**Developed by AlesSystems**")
        lines.append("")
        lines.append("## URL Information")
        lines.append("")
        lines.append(f"- **URL:** `{url}`")
        lines.append(f"- **Scan Date:** {timestamp}")
        lines.append("")
        lines.append("## Security Status")
        lines.append("")
        
        status = verdict.verdict.upper()
        status_emoji = {
            'SAFE': '✅',
            'SUSPICIOUS': '⚠️',
            'DANGEROUS': '🚫'
        }.get(status, '❓')
        
        lines.append(f"**Status:** {status_emoji} {status}")
        lines.append("")
        
        if hasattr(verdict, 'rule_score'):
            lines.append(f"**Risk Score:** {verdict.rule_score}/100")
            lines.append("")
        
        if hasattr(verdict, 'api_data') and verdict.api_data:
            threat_types = verdict.api_data.get('threat_types', [])
            if threat_types:
                lines.append("### Detected Threats")
                lines.append("")
                for threat in threat_types:
                    lines.append(f"- {threat}")
                lines.append("")
        
        if hasattr(verdict, 'reasons') and verdict.reasons:
            lines.append("## Reasons")
            lines.append("")
            for reason in verdict.reasons:
                lines.append(f"- {reason}")
            lines.append("")
        
        lines.append("---")
        lines.append("")
        lines.append("*This report was generated by Link Safety Checker*")
        lines.append("")
        lines.append("*For more information, visit: [GitHub](https://github.com/AlesSystems)*")
        
        return "\n".join(lines)
    
    @staticmethod
    def format_html_report(url, verdict, timestamp=None):
        """Generate HTML report.
        
        Args:
            url: The scanned URL
            verdict: The FinalSecurityVerdict object
            timestamp: Optional timestamp string
            
        Returns:
            Formatted HTML report
        """
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        
        status = verdict.verdict.upper()
        status_emoji = {
            'SAFE': '✅',
            'SUSPICIOUS': '⚠️',
            'DANGEROUS': '🚫'
        }.get(status, '❓')
        
        status_color = {
            'SAFE': '#10b981',
            'SUSPICIOUS': '#f59e0b',
            'DANGEROUS': '#ef4444'
        }.get(status, '#6366f1')
        
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Link Safety Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', 'SF Pro Display', 'Roboto', Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background: #f8fafc;
            color: #1e293b;
        }}
        .header {{
            text-align: center;
            border-bottom: 3px solid {status_color};
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .status-badge {{
            display: inline-block;
            padding: 10px 20px;
            background: {status_color};
            color: white;
            border-radius: 8px;
            font-weight: bold;
            margin: 10px 0;
        }}
        .section {{
            background: white;
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .section h2 {{
            color: {status_color};
            border-bottom: 2px solid {status_color};
            padding-bottom: 10px;
        }}
        .info-item {{
            margin: 10px 0;
        }}
        .info-label {{
            font-weight: bold;
            color: #475569;
        }}
        .url {{
            word-break: break-all;
            background: #f1f5f9;
            padding: 10px;
            border-radius: 4px;
            font-family: 'Consolas', monospace;
        }}
        .footer {{
            text-align: center;
            margin-top: 30px;
            color: #64748b;
            font-size: 0.9em;
        }}
        ul {{
            list-style-type: none;
            padding-left: 0;
        }}
        li:before {{
            content: "• ";
            color: {status_color};
            font-weight: bold;
            margin-right: 8px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🔒 Link Safety Checker</h1>
        <p>Scan Report</p>
        <div class="status-badge">{status_emoji} {status}</div>
    </div>
    
    <div class="section">
        <h2>URL Information</h2>
        <div class="info-item">
            <span class="info-label">URL:</span>
            <div class="url">{url}</div>
        </div>
        <div class="info-item">
            <span class="info-label">Scan Date:</span> {timestamp}
        </div>
    </div>
    
    <div class="section">
        <h2>Security Analysis</h2>
"""
        
        if hasattr(verdict, 'rule_score'):
            html += f"""
        <div class="info-item">
            <span class="info-label">Risk Score:</span> {verdict.rule_score}/100
        </div>
"""
        
        if hasattr(verdict, 'api_data') and verdict.api_data:
            threat_types = verdict.api_data.get('threat_types', [])
            if threat_types:
                html += """
        <div class="info-item">
            <span class="info-label">Detected Threats:</span>
            <ul>
"""
                for threat in threat_types:
                    html += f"                <li>{threat}</li>\n"
                html += """
            </ul>
        </div>
"""
        
        if hasattr(verdict, 'reasons') and verdict.reasons:
            html += """
        <div class="info-item">
            <span class="info-label">Reasons:</span>
            <ul>
"""
            for reason in verdict.reasons:
                html += f"                <li>{reason}</li>\n"
            html += """
            </ul>
        </div>
"""
        
        html += """
    </div>
    
    <div class="footer">
        <p>This report was generated by <strong>Link Safety Checker</strong></p>
        <p>Developed by AlesSystems</p>
    </div>
</body>
</html>
"""
        return html
    
    @staticmethod
    def format_json_report(url, verdict, timestamp=None):
        """Generate JSON report.
        
        Args:
            url: The scanned URL
            verdict: The FinalSecurityVerdict object
            timestamp: Optional timestamp string
            
        Returns:
            JSON formatted report string
        """
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        
        report = {
            "scan_date": timestamp,
            "url": url,
            "status": verdict.verdict,
            "rule_score": getattr(verdict, 'rule_score', None),
            "api_available": getattr(verdict, 'api_available', False),
            "threat_types": [],
            "reasons": getattr(verdict, 'reasons', []),
            "metadata": {
                "tool": "Link Safety Checker - AlesSystems",
                "version": "1.0"
            }
        }
        
        if hasattr(verdict, 'api_data') and verdict.api_data:
            report["threat_types"] = verdict.api_data.get('threat_types', [])
        
        return json.dumps(report, indent=2)
    
    @staticmethod
    def format_social_media(url, verdict, platform='generic'):
        """Generate social media formatted post.
        
        Args:
            url: The scanned URL
            verdict: The FinalSecurityVerdict object
            platform: Platform name (twitter, facebook, linkedin, generic)
            
        Returns:
            Formatted social media post
        """
        status = verdict.verdict.upper()
        status_emoji = {
            'SAFE': '✅',
            'SUSPICIOUS': '⚠️',
            'DANGEROUS': '🚫'
        }.get(status, '❓')
        
        if platform == 'twitter':
            # Twitter has 280 character limit
            msg = f"{status_emoji} URL Safety Check: {status}\n"
            msg += f"URL: {url[:100]}{'...' if len(url) > 100 else ''}\n"
            msg += f"#CyberSecurity #URLSafety"
            return msg[:280]
        
        elif platform == 'facebook':
            msg = f"{status_emoji} Link Safety Check Result\n\n"
            msg += f"Status: {status}\n"
            msg += f"URL: {url}\n\n"
            if hasattr(verdict, 'reasons') and verdict.reasons:
                msg += f"Key findings: {verdict.reasons[0]}\n\n"
            msg += "Scanned with Link Safety Checker by AlesSystems"
            return msg
        
        elif platform == 'linkedin':
            msg = f"🔒 Link Safety Analysis Report\n\n"
            msg += f"Status: {status_emoji} {status}\n"
            msg += f"URL: {url}\n\n"
            if hasattr(verdict, 'rule_score'):
                msg += f"Risk Score: {verdict.rule_score}/100\n\n"
            msg += "Stay safe online! Always verify links before clicking.\n\n"
            msg += "#CyberSecurity #InfoSec #URLSafety #LinkSafetyChecker"
            return msg
        
        else:  # generic
            msg = f"{status_emoji} URL Safety Check: {status}\n"
            msg += f"URL: {url}\n"
            if hasattr(verdict, 'rule_score'):
                msg += f"Risk Score: {verdict.rule_score}/100\n"
            msg += "\nScanned with Link Safety Checker"
            return msg
    
    @staticmethod
    def generate_qr_code(url, verdict):
        """Generate QR code for scan results.
        
        Args:
            url: The scanned URL
            verdict: The FinalSecurityVerdict object
            
        Returns:
            PIL Image object with QR code, or None if qrcode not available
        """
        if not QR_AVAILABLE:
            return None
        
        # Create data for QR code
        qr_data = {
            "url": url,
            "status": verdict.verdict,
            "scanned_by": "Link Safety Checker - AlesSystems"
        }
        
        # Create QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(json.dumps(qr_data))
        qr.make(fit=True)
        
        img = qr.make_image(fill_color="black", back_color="white")
        return img
    
    @staticmethod
    def copy_to_clipboard(text):
        """Copy text to clipboard.
        
        Args:
            text: Text to copy
            
        Returns:
            True if successful, False otherwise
        """
        if PYPERCLIP_AVAILABLE:
            try:
                pyperclip.copy(text)
                return True
            except:
                return False
        return False


class ShareDialog:
    """Dialog for sharing scan results."""
    
    def __init__(self, parent, url, verdict):
        """Initialize share dialog.
        
        Args:
            parent: Parent tkinter window
            url: The scanned URL
            verdict: The FinalSecurityVerdict object
        """
        self.parent = parent
        self.url = url
        self.verdict = verdict
        self.timestamp = datetime.now().isoformat()
        self.dialog = None
        
    def show(self):
        """Show the share dialog."""
        self.dialog = tk.Toplevel(self.parent)
        self.dialog.title("Share Results")
        self.dialog.geometry("500x600")
        self.dialog.configure(bg="#1a1a2e")
        self.dialog.resizable(False, False)
        
        # Make dialog modal
        self.dialog.transient(self.parent)
        self.dialog.grab_set()
        
        # Header
        header = tk.Label(
            self.dialog,
            text="📤 Share Scan Results",
            font=("Segoe UI", 16, "bold"),
            bg="#1a1a2e",
            fg="#00d4ff"
        )
        header.pack(pady=20)
        
        # Format options frame
        options_frame = tk.Frame(self.dialog, bg="#1a1a2e")
        options_frame.pack(fill=tk.BOTH, expand=True, padx=20, pady=10)
        
        # Text formats
        tk.Label(
            options_frame,
            text="📄 Text Formats",
            font=("Segoe UI", 12, "bold"),
            bg="#1a1a2e",
            fg="#ffffff"
        ).pack(anchor=tk.W, pady=(0, 10))
        
        self._create_button(options_frame, "Copy as Plain Text", self.copy_text)
        self._create_button(options_frame, "Copy as Markdown", self.copy_markdown)
        self._create_button(options_frame, "Copy as HTML", self.copy_html)
        self._create_button(options_frame, "Copy as JSON", self.copy_json)
        
        # QR Code
        tk.Label(
            options_frame,
            text="📱 QR Code",
            font=("Segoe UI", 12, "bold"),
            bg="#1a1a2e",
            fg="#ffffff"
        ).pack(anchor=tk.W, pady=(20, 10))
        
        if QR_AVAILABLE:
            self._create_button(options_frame, "Generate QR Code", self.show_qr_code)
        else:
            tk.Label(
                options_frame,
                text="⚠️ Install 'qrcode[pil]' to enable QR codes",
                font=("Segoe UI", 9, "italic"),
                bg="#1a1a2e",
                fg="#f59e0b"
            ).pack(anchor=tk.W, padx=20)
        
        # Social Media
        tk.Label(
            options_frame,
            text="🌐 Social Media",
            font=("Segoe UI", 12, "bold"),
            bg="#1a1a2e",
            fg="#ffffff"
        ).pack(anchor=tk.W, pady=(20, 10))
        
        self._create_button(options_frame, "Twitter/X Format", lambda: self.copy_social('twitter'))
        self._create_button(options_frame, "Facebook Format", lambda: self.copy_social('facebook'))
        self._create_button(options_frame, "LinkedIn Format", lambda: self.copy_social('linkedin'))
        
        # Close button
        close_btn = tk.Button(
            self.dialog,
            text="Close",
            command=self.dialog.destroy,
            font=("Segoe UI", 11, "bold"),
            bg="#ef4444",
            fg="#ffffff",
            activebackground="#dc2626",
            activeforeground="#ffffff",
            cursor="hand2",
            relief=tk.FLAT,
            padx=30,
            pady=10
        )
        close_btn.pack(pady=20)
    
    def _create_button(self, parent, text, command):
        """Create a styled button for the dialog."""
        btn = tk.Button(
            parent,
            text=text,
            command=command,
            font=("Segoe UI", 10),
            bg="#2d2d44",
            fg="#00d4ff",
            activebackground="#00d4ff",
            activeforeground="#1a1a2e",
            cursor="hand2",
            relief=tk.FLAT,
            padx=20,
            pady=8,
            anchor=tk.W
        )
        btn.pack(fill=tk.X, pady=5)
        return btn
    
    def copy_text(self):
        """Copy plain text report to clipboard."""
        report = ShareManager.format_text_report(self.url, self.verdict, self.timestamp)
        if ShareManager.copy_to_clipboard(report):
            messagebox.showinfo("Success", "Text report copied to clipboard!", parent=self.dialog)
        else:
            messagebox.showerror("Error", "Failed to copy to clipboard.", parent=self.dialog)
    
    def copy_markdown(self):
        """Copy Markdown report to clipboard."""
        report = ShareManager.format_markdown_report(self.url, self.verdict, self.timestamp)
        if ShareManager.copy_to_clipboard(report):
            messagebox.showinfo("Success", "Markdown report copied to clipboard!", parent=self.dialog)
        else:
            messagebox.showerror("Error", "Failed to copy to clipboard.", parent=self.dialog)
    
    def copy_html(self):
        """Copy HTML report to clipboard."""
        report = ShareManager.format_html_report(self.url, self.verdict, self.timestamp)
        if ShareManager.copy_to_clipboard(report):
            messagebox.showinfo("Success", "HTML report copied to clipboard!", parent=self.dialog)
        else:
            messagebox.showerror("Error", "Failed to copy to clipboard.", parent=self.dialog)
    
    def copy_json(self):
        """Copy JSON report to clipboard."""
        report = ShareManager.format_json_report(self.url, self.verdict, self.timestamp)
        if ShareManager.copy_to_clipboard(report):
            messagebox.showinfo("Success", "JSON report copied to clipboard!", parent=self.dialog)
        else:
            messagebox.showerror("Error", "Failed to copy to clipboard.", parent=self.dialog)
    
    def copy_social(self, platform):
        """Copy social media format to clipboard."""
        report = ShareManager.format_social_media(self.url, self.verdict, platform)
        if ShareManager.copy_to_clipboard(report):
            messagebox.showinfo("Success", f"{platform.title()} format copied to clipboard!", parent=self.dialog)
        else:
            messagebox.showerror("Error", "Failed to copy to clipboard.", parent=self.dialog)
    
    def show_qr_code(self):
        """Show QR code in a new window."""
        if not QR_AVAILABLE:
            messagebox.showerror("Error", "QR code library not available. Install 'qrcode[pil]'", parent=self.dialog)
            return
        
        img = ShareManager.generate_qr_code(self.url, self.verdict)
        if not img:
            messagebox.showerror("Error", "Failed to generate QR code.", parent=self.dialog)
            return
        
        # Create QR code window
        qr_window = tk.Toplevel(self.dialog)
        qr_window.title("QR Code")
        qr_window.configure(bg="#1a1a2e")
        qr_window.resizable(False, False)
        
        # Header
        header = tk.Label(
            qr_window,
            text="📱 Scan Results QR Code",
            font=("Segoe UI", 14, "bold"),
            bg="#1a1a2e",
            fg="#00d4ff"
        )
        header.pack(pady=15)
        
        # Convert PIL image to PhotoImage
        photo = ImageTk.PhotoImage(img)
        
        # Display QR code
        label = tk.Label(qr_window, image=photo, bg="#ffffff")
        label.image = photo  # Keep a reference
        label.pack(padx=20, pady=10)
        
        # Info
        info = tk.Label(
            qr_window,
            text=f"URL: {self.url[:50]}{'...' if len(self.url) > 50 else ''}",
            font=("Segoe UI", 9),
            bg="#1a1a2e",
            fg="#b8b8d1"
        )
        info.pack(pady=5)
        
        # Buttons frame
        btn_frame = tk.Frame(qr_window, bg="#1a1a2e")
        btn_frame.pack(pady=15)
        
        # Save button
        save_btn = tk.Button(
            btn_frame,
            text="💾 Save as PNG",
            command=lambda: self.save_qr_code(img),
            font=("Segoe UI", 10),
            bg="#00ff88",
            fg="#0f2027",
            activebackground="#00d4ff",
            activeforeground="#0f2027",
            cursor="hand2",
            relief=tk.FLAT,
            padx=20,
            pady=8
        )
        save_btn.pack(side=tk.LEFT, padx=5)
        
        # Close button
        close_btn = tk.Button(
            btn_frame,
            text="Close",
            command=qr_window.destroy,
            font=("Segoe UI", 10),
            bg="#2d2d44",
            fg="#00d4ff",
            activebackground="#00d4ff",
            activeforeground="#1a1a2e",
            cursor="hand2",
            relief=tk.FLAT,
            padx=20,
            pady=8
        )
        close_btn.pack(side=tk.LEFT, padx=5)
    
    def save_qr_code(self, img):
        """Save QR code as PNG file."""
        filename = filedialog.asksaveasfilename(
            parent=self.dialog,
            title="Save QR Code",
            defaultextension=".png",
            filetypes=[("PNG files", "*.png"), ("All files", "*.*")],
            initialfile=f"qr_code_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        )
        
        if filename:
            try:
                img.save(filename)
                messagebox.showinfo("Success", f"QR code saved to:\n{filename}", parent=self.dialog)
            except Exception as e:
                messagebox.showerror("Error", f"Failed to save QR code:\n{str(e)}", parent=self.dialog)
